spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sql_prod
    username: sql_prod_user
    password: yoo
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
